name: example
description: Example app for form_builder_validators
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_builder_validators:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
