name: form_builder_validators
description: Form Builder Validators set of validators for FlutterFormBuilder. Provides common validators and a way to make your own.
version: 11.1.2
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_validators
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues
homepage: https://github.com/flutter-form-builder-ecosystem
topics:
  - form
  - validator
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.20.0 <0.21.0"

dev_dependencies:
  faker_dart: ^0.2.2
  flutter_lints: ">=6.0.0"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
